In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.3

In [3]:
s = pd.Series()
print(s)

Series([], dtype: object)

In [4]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: str

In [6]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
s

100    a
101    b
102    c
103    d
dtype: str

In [7]:
# create a dict in series
data = {'a':0,'b':1,'c':3}
s = pd.Series(data)
print(s)

a    0
b    1
c    3
dtype: int64

In [12]:
# 
data = {'a':0,'b':1,'c':2}
s = pd.Series(data,index=['b','c','d','a'],dtype = int)
print(s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [17]:
#accessing datas from series
s = pd.Series([1,2,3,4,5])
print(s)
print(s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64
2

In [16]:
print(s[1:5])

1    2
2    3
3    4
4    5
dtype: int64

In [23]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s['b':'d'])
print(s[['a','c','d']])

b    2
c    3
d    4
dtype: int64
a    1
c    3
d    4
dtype: int64

In [25]:
#  creating an empty data frames
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [28]:
#  creating a data Frame from a list
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [31]:
# dataframe from dict
data = {'Name':['A','B','C','D'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   28
1    B   34
2    C   29
3    D   42

In [36]:
# DCreate a data from a dict of series
data = {'one':pd.Series([1,2,3],index=['a','b','c']),
        'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df = pd.DataFrame(data)
print(df)
# select a single column
print(df['one'])
print(df['two'])
print(df[['one','two']])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64
a    1
b    2
c    3
d    4
Name: two, dtype: int64
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [40]:
# adding new column
df['three'] = pd.Series([10,20,30],index=['a','b','c'])
df

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [46]:
from numpy.random import randn
df = pd.DataFrame(randn(5,5),index='A B C D E'.split(),columns = 'V W X Y Z'.split())
df

          V         W         X         Y         Z
A -0.267987 -2.961831 -0.118968  0.019525 -0.722875
B -1.461500 -0.080547  0.268050  1.219835  1.034437
C  0.442220  0.292973 -0.656727  0.429676  0.098619
D -0.943241 -1.671292  0.022824  0.164997  0.766892
E -0.315471  1.642928 -0.791601 -0.422200 -2.029173

In [54]:
# labled based selection to displat the specific rows
df.loc['B']

np.float64(1.2198348135698398)

In [53]:
# index based
df.iloc[2]

V    0.442220
W    0.292973
X   -0.656727
Y    0.429676
Z    0.098619
Name: C, dtype: float64

In [60]:
a=df.loc[['A','B'],['W','Y']]
a

          W         Y
A -2.961831  0.019525
B -0.080547  1.219835