In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.3

In [3]:
s = pd.Series()
print(s)

Series([], dtype: object)

In [4]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: str

In [5]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
s

100    a
101    b
102    c
103    d
dtype: str

In [6]:
# create a dict in series
data = {'a':0,'b':1,'c':3}
s = pd.Series(data)
print(s)

a    0
b    1
c    3
dtype: int64

In [7]:
# 
data = {'a':0,'b':1,'c':2}
s = pd.Series(data,index=['b','c','d','a'],dtype = int)
print(s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [8]:
#accessing datas from series
s = pd.Series([1,2,3,4,5])
print(s)
print(s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64
2

In [9]:
print(s[1:5])

1    2
2    3
3    4
4    5
dtype: int64

In [10]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s['b':'d'])
print(s[['a','c','d']])

b    2
c    3
d    4
dtype: int64
a    1
c    3
d    4
dtype: int64

In [11]:
#  creating an empty data frames
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [12]:
#  creating a data Frame from a list
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [13]:
# dataframe from dict
data = {'Name':['A','B','C','D'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   28
1    B   34
2    C   29
3    D   42

In [14]:
# DCreate a data from a dict of series
data = {'one':pd.Series([1,2,3],index=['a','b','c']),
        'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df = pd.DataFrame(data)
print(df)
# select a single column
print(df['one'])
print(df['two'])
print(df[['one','two']])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64
a    1
b    2
c    3
d    4
Name: two, dtype: int64
   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [15]:
# adding new column
df['three'] = pd.Series([10,20,30],index=['a','b','c'])
df

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [16]:
from numpy.random import randn
df = pd.DataFrame(randn(5,5),index='A B C D E'.split(),columns = 'V W X Y Z'.split())
df

          V         W         X         Y         Z
A -0.114233  1.056270  0.540002  0.498219  1.357250
B  0.099479 -0.284638  0.409387  0.914965  0.424433
C -1.310045  0.048744 -2.080541  2.032856 -0.210592
D -0.343980 -0.297936  0.098070 -0.732923  1.002454
E -1.150083  0.352712  0.740523 -2.300378 -1.079470

In [17]:
# labled based selection to displat the specific rows
df.loc['B']

V    0.099479
W   -0.284638
X    0.409387
Y    0.914965
Z    0.424433
Name: B, dtype: float64

In [18]:
# index based
df.iloc[2]

V   -1.310045
W    0.048744
X   -2.080541
Y    2.032856
Z   -0.210592
Name: C, dtype: float64

In [19]:
a=df.loc[['A','B'],['W','Y']]
a

          W         Y
A  1.056270  0.498219
B -0.284638  0.914965

In [20]:
df['new'] = df['W']+df['Z']
df

          V         W         X         Y         Z       new
A -0.114233  1.056270  0.540002  0.498219  1.357250  2.413520
B  0.099479 -0.284638  0.409387  0.914965  0.424433  0.139795
C -1.310045  0.048744 -2.080541  2.032856 -0.210592 -0.161847
D -0.343980 -0.297936  0.098070 -0.732923  1.002454  0.704519
E -1.150083  0.352712  0.740523 -2.300378 -1.079470 -0.726758

In [21]:
df['new1']=[1,2,3,4,5]
df

          V         W         X         Y         Z       new  new1
A -0.114233  1.056270  0.540002  0.498219  1.357250  2.413520     1
B  0.099479 -0.284638  0.409387  0.914965  0.424433  0.139795     2
C -1.310045  0.048744 -2.080541  2.032856 -0.210592 -0.161847     3
D -0.343980 -0.297936  0.098070 -0.732923  1.002454  0.704519     4
E -1.150083  0.352712  0.740523 -2.300378 -1.079470 -0.726758     5

In [22]:
df['hai'] = 100
df

          V         W         X         Y         Z       new  new1  hai
A -0.114233  1.056270  0.540002  0.498219  1.357250  2.413520     1  100
B  0.099479 -0.284638  0.409387  0.914965  0.424433  0.139795     2  100
C -1.310045  0.048744 -2.080541  2.032856 -0.210592 -0.161847     3  100
D -0.343980 -0.297936  0.098070 -0.732923  1.002454  0.704519     4  100
E -1.150083  0.352712  0.740523 -2.300378 -1.079470 -0.726758     5  100

In [23]:
# delete a colums for temporary
df.drop('new',axis=1)

          V         W         X         Y         Z  new1  hai
A -0.114233  1.056270  0.540002  0.498219  1.357250     1  100
B  0.099479 -0.284638  0.409387  0.914965  0.424433     2  100
C -1.310045  0.048744 -2.080541  2.032856 -0.210592     3  100
D -0.343980 -0.297936  0.098070 -0.732923  1.002454     4  100
E -1.150083  0.352712  0.740523 -2.300378 -1.079470     5  100

In [24]:
df

          V         W         X         Y         Z       new  new1  hai
A -0.114233  1.056270  0.540002  0.498219  1.357250  2.413520     1  100
B  0.099479 -0.284638  0.409387  0.914965  0.424433  0.139795     2  100
C -1.310045  0.048744 -2.080541  2.032856 -0.210592 -0.161847     3  100
D -0.343980 -0.297936  0.098070 -0.732923  1.002454  0.704519     4  100
E -1.150083  0.352712  0.740523 -2.300378 -1.079470 -0.726758     5  100

In [25]:
df.drop('new',axis=1,inplace=True)
df.drop('E',axis=0,inplace = True)

In [26]:
df

          V         W         X         Y         Z  new1  hai
A -0.114233  1.056270  0.540002  0.498219  1.357250     1  100
B  0.099479 -0.284638  0.409387  0.914965  0.424433     2  100
C -1.310045  0.048744 -2.080541  2.032856 -0.210592     3  100
D -0.343980 -0.297936  0.098070 -0.732923  1.002454     4  100

In [27]:
del df['hai']

In [28]:
df

          V         W         X         Y         Z  new1
A -0.114233  1.056270  0.540002  0.498219  1.357250     1
B  0.099479 -0.284638  0.409387  0.914965  0.424433     2
C -1.310045  0.048744 -2.080541  2.032856 -0.210592     3
D -0.343980 -0.297936  0.098070 -0.732923  1.002454     4

In [29]:
df.pop('new1')

A    1
B    2
C    3
D    4
Name: new1, dtype: int64

In [30]:
df

          V         W         X         Y         Z
A -0.114233  1.056270  0.540002  0.498219  1.357250
B  0.099479 -0.284638  0.409387  0.914965  0.424433
C -1.310045  0.048744 -2.080541  2.032856 -0.210592
D -0.343980 -0.297936  0.098070 -0.732923  1.002454

In [31]:
df1 = pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2 = pd.DataFrame([[5,6],[7,8]],columns=['a','b'])
# print(df1)
# print(df2)
df = pd.concat([df1,df2])
print(df)
print("---------------")
df = pd.concat([df1,df2],ignore_index = True)
df

   a  b
0  1  2
1  3  4
0  5  6
1  7  8
---------------

   a  b
0  1  2
1  3  4
2  5  6
3  7  8

In [32]:
df = pd.DataFrame(np.random.randn(5,5),columns='V W X Y Z'.split())
df

          V         W         X         Y         Z
0  0.269046  2.475607  2.043267 -0.279802  1.956243
1  0.554903 -0.872539 -0.423795 -1.049483 -0.443951
2 -0.430279 -0.595864  1.376858 -1.638413 -0.168200
3 -0.437138  0.369595  1.003589  1.026300 -1.359362
4 -0.316719  0.320495  1.213272  1.257489 -0.242714

In [34]:
df.drop([0],axis=0,inplace=True)
df.drop([4],axis=0,inplace=True)

KeyError: '[0] not found in axis'

In [35]:
df.drop([4],axis=0,inplace=True)

In [36]:
df

          V         W         X         Y         Z
1  0.554903 -0.872539 -0.423795 -1.049483 -0.443951
2 -0.430279 -0.595864  1.376858 -1.638413 -0.168200
3 -0.437138  0.369595  1.003589  1.026300 -1.359362

In [37]:
df.reset_index(drop=True)

          V         W         X         Y         Z
0  0.554903 -0.872539 -0.423795 -1.049483 -0.443951
1 -0.430279 -0.595864  1.376858 -1.638413 -0.168200
2 -0.437138  0.369595  1.003589  1.026300 -1.359362

In [38]:
df.set_index('V')

                  W         X         Y         Z
V
 0.554903 -0.872539 -0.423795 -1.049483 -0.443951
-0.430279 -0.595864  1.376858 -1.638413 -0.168200
-0.437138  0.369595  1.003589  1.026300 -1.359362

In [39]:
df.reset_index()

   index         V         W         X         Y         Z
0      1  0.554903 -0.872539 -0.423795 -1.049483 -0.443951
1      2 -0.430279 -0.595864  1.376858 -1.638413 -0.168200
2      3 -0.437138  0.369595  1.003589  1.026300 -1.359362

In [40]:
df.reset_index()

   index         V         W         X         Y         Z
0      1  0.554903 -0.872539 -0.423795 -1.049483 -0.443951
1      2 -0.430279 -0.595864  1.376858 -1.638413 -0.168200
2      3 -0.437138  0.369595  1.003589  1.026300 -1.359362

In [41]:
df.reset_index(drop=True)

          V         W         X         Y         Z
0  0.554903 -0.872539 -0.423795 -1.049483 -0.443951
1 -0.430279 -0.595864  1.376858 -1.638413 -0.168200
2 -0.437138  0.369595  1.003589  1.026300 -1.359362

In [45]:
a=df.set_index("Z")
a

                  V         W         X         Y
Z
-0.443951  0.554903 -0.872539 -0.423795 -1.049483
-0.168200 -0.430279 -0.595864  1.376858 -1.638413
-1.359362 -0.437138  0.369595  1.003589  1.026300